### PR TITLE
Change README.rst to README.md

### PR DESCRIPTION
**Pull request by drevantonder**
#3

### CODE REVIEW

**Comment by brejoc** [comment]
@DrevanTonder Thanks for your contribution. But you've been missing one detail. The [description here](https://pypi.python.org/pypi/django-intercoolerjs/1.1.2.0) is auto-generated from the rst file. This should also work with markdown. Please take a look at [this comment](https://github.com/brejoc/django-intercoolerjs/issues/3#issuecomment-288977786).

**Comment by drevantonder** [comment]
So I need to include
```python
try:
    import pypandoc
    long_description = pypandoc.convert('README.md', 'rst')
except ImportError:
    long_description = open('README.md').read()
``` 
in the setup.py?

**Comment by brejoc** [comment]
You would have to replace [this](https://github.com/brejoc/django-intercoolerjs/blob/master/setup.py#L8-L9). But it would also be nice, if you could test the result somehw.

**Comment by drevantonder** [comment]
Thought so, just don't want to break anything. :)

**Comment by drevantonder** [comment]
It converts fine but:

It may be a problem if [`pandoc`](https://pandoc.org/) is not installed so I added `OSError` to the tuple of the `except`. 

https://github.com/DrevanTonder/django-intercoolerjs/blob/master/setup.py#L11

Now the file will convert into `.rst` if `pypandoc` (`pandoc` will need to be installed too) is installed.
If `pypandoc` or `pandoc` is missing the file will still be in Markdown format.

**Comment by brejoc** [comment]
@DrevanTonder Looks good. But why the `OSError`? Did you get that during you tests? If `pypandoc` is not installed, shouldn't catching the `ImportError` be enough?

**Comment by drevantonder** [comment]
if `pypandoc` is not installed the `ImportError` helps.

if `pypandoc` is installed but `pandoc` is not it raises `OSError` (`pandoc` is needed by `pypandoc` to convert)

**Comment by brejoc** [comment]
Thanks for the clarification!

**Comment by brejoc** [comment]
I've just merged the branch. Many thanks for your contribution, @DrevanTonder! 👍

**Pull request merged**
